[package]
name = "cargo-blazingly"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Development and production CLI for Blazingly applications"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
blazingly-docs.workspace = true
blazingly-json.workspace = true
ctrlc.workspace = true
serde = { workspace = true, features = ["std"] }
toml.workspace = true

[lints]
workspace = true
